/**
 * Scheme-agnostic primitive tokens — flat, dotted-key data.
 *
 * GENERATED-STYLE SOURCE: this file is plain data (no imports, no types).
 * It is intended to be replaced by the Figma design-system export. Keys use a
 * fully-flat `a.b.c` path; the runtime theme is rebuilt from these via
 * `unflatten()` in `theme.ts`. Scalar leaves only.
 *
 * `palette.*` is kept for Figma parity / authoring reference; the runtime theme
 * consumes already-resolved semantic colors (see `light.ts` / `dark.ts`) and
 * does not read the palette directly.
 */
export const primitives = {
  // ── palette (Tailwind-derived ramps) ──────────────────────────────────────
  'palette.slate.50': '#f8fafc',
  'palette.slate.100': '#f1f5f9',
  'palette.slate.200': '#e2e8f0',
  'palette.slate.300': '#cad5e2',
  'palette.slate.400': '#90a1b9',
  'palette.slate.500': '#62748e',
  'palette.slate.600': '#45556c',
  'palette.slate.700': '#314158',
  'palette.slate.800': '#1d293d',
  'palette.slate.900': '#0f172b',
  'palette.slate.950': '#020618',
  'palette.emerald.50': '#ecfdf5',
  'palette.emerald.100': '#d0fae5',
  'palette.emerald.200': '#a4f4cf',
  'palette.emerald.300': '#5ee9b5',
  'palette.emerald.400': '#00d492',
  'palette.emerald.500': '#00bc7d',
  'palette.emerald.600': '#009966',
  'palette.emerald.700': '#007a55',
  'palette.emerald.800': '#006045',
  'palette.emerald.900': '#004f3b',
  'palette.emerald.950': '#002c22',
  'palette.red.50': '#fef2f2',
  'palette.red.100': '#ffe2e2',
  'palette.red.200': '#ffc9c9',
  'palette.red.300': '#ffa2a2',
  'palette.red.400': '#ff6467',
  'palette.red.500': '#fb2c36',
  'palette.red.600': '#e7000b',
  'palette.red.700': '#c10007',
  'palette.red.800': '#9f0712',
  'palette.red.900': '#82181a',
  'palette.red.950': '#460809',
  'palette.amber.50': '#fffbeb',
  'palette.amber.100': '#fef3c6',
  'palette.amber.200': '#fee685',
  'palette.amber.300': '#ffd230',
  'palette.amber.400': '#ffb900',
  'palette.amber.500': '#fe9a00',
  'palette.amber.600': '#e17100',
  'palette.amber.700': '#bb4d00',
  'palette.amber.800': '#973c00',
  'palette.amber.900': '#7b3306',
  'palette.amber.950': '#461901',
  'palette.green.50': '#f0fdf4',
  'palette.green.100': '#dcfce7',
  'palette.green.200': '#b9f8cf',
  'palette.green.300': '#7bf1a8',
  'palette.green.400': '#05df72',
  'palette.green.500': '#00c950',
  'palette.green.600': '#00a63e',
  'palette.green.700': '#008236',
  'palette.green.800': '#016630',
  'palette.green.900': '#0d542b',
  'palette.green.950': '#032e15',
  'palette.blue.50': '#eff6ff',
  'palette.blue.100': '#dbeafe',
  'palette.blue.200': '#bedbff',
  'palette.blue.300': '#8ec5ff',
  'palette.blue.400': '#51a2ff',
  'palette.blue.500': '#2b7fff',
  'palette.blue.600': '#155dfc',
  'palette.blue.700': '#1447e6',
  'palette.blue.800': '#193cb8',
  'palette.blue.900': '#1c398e',
  'palette.blue.950': '#162456',
  'palette.sky.50': '#f0f9ff',
  'palette.sky.100': '#dff2fe',
  'palette.sky.200': '#b8e6fe',
  'palette.sky.300': '#74d4ff',
  'palette.sky.400': '#00bcff',
  'palette.sky.500': '#00a6f4',
  'palette.sky.600': '#0084d1',
  'palette.sky.700': '#0069a8',
  'palette.sky.800': '#00598a',
  'palette.sky.900': '#024a70',
  'palette.sky.950': '#052f4a',
  'palette.black': '#000000',
  'palette.white': '#ffffff',

  // ── spacing scale (dp, 4dp base unit) ─────────────────────────────────────
  'spacing.0': 0,
  'spacing.1': 4,
  'spacing.2': 8,
  'spacing.3': 12,
  'spacing.4': 16,
  'spacing.5': 20,
  'spacing.6': 24,
  'spacing.7': 28,
  'spacing.8': 32,
  'spacing.9': 36,
  'spacing.10': 40,
  'spacing.12': 48,
  'spacing.14': 56,
  'spacing.16': 64,
  'spacing.20': 80,
  'spacing.24': 96,
  'spacing.32': 128,

  // ── border-radius scale (dp) ──────────────────────────────────────────────
  'radius.none': 0,
  'radius.xs': 2,
  'radius.sm': 4,
  'radius.md': 6,
  'radius.lg': 8,
  'radius.xl': 12,
  'radius.2xl': 16,
  'radius.3xl': 24,
  'radius.full': 9999,

  // ── typography: weight-token → font family (System default) ───────────────
  'typography.fonts.regular': 'System',
  'typography.fonts.medium': 'System',
  'typography.fonts.semibold': 'System',
  'typography.fonts.bold': 'System',

  // ── typography: role variants ─────────────────────────────────────────────
  'typography.variants.display-lg.fontSize': 57,
  'typography.variants.display-lg.lineHeight': 64,
  'typography.variants.display-lg.fontWeight': 'regular',
  'typography.variants.display-lg.letterSpacing': -0.25,
  'typography.variants.display-lg.maxFontSizeMultiplier': 1.2,
  'typography.variants.display-md.fontSize': 45,
  'typography.variants.display-md.lineHeight': 52,
  'typography.variants.display-md.fontWeight': 'regular',
  'typography.variants.display-md.letterSpacing': 0,
  'typography.variants.display-md.maxFontSizeMultiplier': 1.2,
  'typography.variants.display-sm.fontSize': 36,
  'typography.variants.display-sm.lineHeight': 44,
  'typography.variants.display-sm.fontWeight': 'regular',
  'typography.variants.display-sm.letterSpacing': 0,
  'typography.variants.display-sm.maxFontSizeMultiplier': 1.2,
  'typography.variants.headline-lg.fontSize': 32,
  'typography.variants.headline-lg.lineHeight': 40,
  'typography.variants.headline-lg.fontWeight': 'semibold',
  'typography.variants.headline-lg.letterSpacing': 0,
  'typography.variants.headline-lg.maxFontSizeMultiplier': 1.3,
  'typography.variants.headline-md.fontSize': 28,
  'typography.variants.headline-md.lineHeight': 36,
  'typography.variants.headline-md.fontWeight': 'semibold',
  'typography.variants.headline-md.letterSpacing': 0,
  'typography.variants.headline-md.maxFontSizeMultiplier': 1.3,
  'typography.variants.headline-sm.fontSize': 24,
  'typography.variants.headline-sm.lineHeight': 32,
  'typography.variants.headline-sm.fontWeight': 'semibold',
  'typography.variants.headline-sm.letterSpacing': 0,
  'typography.variants.headline-sm.maxFontSizeMultiplier': 1.3,
  'typography.variants.title-lg.fontSize': 20,
  'typography.variants.title-lg.lineHeight': 28,
  'typography.variants.title-lg.fontWeight': 'semibold',
  'typography.variants.title-lg.letterSpacing': 0,
  'typography.variants.title-lg.maxFontSizeMultiplier': 1.4,
  'typography.variants.title-md.fontSize': 18,
  'typography.variants.title-md.lineHeight': 26,
  'typography.variants.title-md.fontWeight': 'semibold',
  'typography.variants.title-md.letterSpacing': 0,
  'typography.variants.title-md.maxFontSizeMultiplier': 1.4,
  'typography.variants.title-sm.fontSize': 16,
  'typography.variants.title-sm.lineHeight': 24,
  'typography.variants.title-sm.fontWeight': 'semibold',
  'typography.variants.title-sm.letterSpacing': 0.1,
  'typography.variants.title-sm.maxFontSizeMultiplier': 1.4,
  'typography.variants.body-lg.fontSize': 18,
  'typography.variants.body-lg.lineHeight': 28,
  'typography.variants.body-lg.fontWeight': 'regular',
  'typography.variants.body-lg.letterSpacing': 0,
  'typography.variants.body-lg.maxFontSizeMultiplier': 1.8,
  'typography.variants.body-md.fontSize': 16,
  'typography.variants.body-md.lineHeight': 24,
  'typography.variants.body-md.fontWeight': 'regular',
  'typography.variants.body-md.letterSpacing': 0.15,
  'typography.variants.body-md.maxFontSizeMultiplier': 1.8,
  'typography.variants.body-sm.fontSize': 14,
  'typography.variants.body-sm.lineHeight': 20,
  'typography.variants.body-sm.fontWeight': 'regular',
  'typography.variants.body-sm.letterSpacing': 0.25,
  'typography.variants.body-sm.maxFontSizeMultiplier': 1.8,
  'typography.variants.label-lg.fontSize': 16,
  'typography.variants.label-lg.lineHeight': 24,
  'typography.variants.label-lg.fontWeight': 'medium',
  'typography.variants.label-lg.letterSpacing': 0.1,
  'typography.variants.label-lg.maxFontSizeMultiplier': 1.5,
  'typography.variants.label-md.fontSize': 14,
  'typography.variants.label-md.lineHeight': 20,
  'typography.variants.label-md.fontWeight': 'medium',
  'typography.variants.label-md.letterSpacing': 0.5,
  'typography.variants.label-md.maxFontSizeMultiplier': 1.5,
  'typography.variants.label-sm.fontSize': 12,
  'typography.variants.label-sm.lineHeight': 16,
  'typography.variants.label-sm.fontWeight': 'medium',
  'typography.variants.label-sm.letterSpacing': 0.5,
  'typography.variants.label-sm.maxFontSizeMultiplier': 1.5,
  'typography.variants.caption.fontSize': 12,
  'typography.variants.caption.lineHeight': 16,
  'typography.variants.caption.fontWeight': 'regular',
  'typography.variants.caption.letterSpacing': 0.4,
  'typography.variants.caption.maxFontSizeMultiplier': 1.4,

  // ── state-layer opacities ─────────────────────────────────────────────────
  'opacity.disabled': 0.45,
  'opacity.pressed': 0.85,

  // ── screen-level layout ───────────────────────────────────────────────────
  'layout.screen.margin.x': 16,
  'layout.screen.margin.y': 0,
};
